//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ItemMaster
    {
        [Key]
        public int ItemCode { get; set; }
        [Required(AllowEmptyStrings =false,ErrorMessage ="Please Enter item Name")]
        public string ItemName { get; set; }
        [Required(AllowEmptyStrings =false,ErrorMessage ="Please Enter item Name")]
        public string ItemType { get; set; }
        public string HSNCODE { get; set; }
        [Range(0,100,ErrorMessage ="Please Enter Valid Gst")]
        public string GstPer { get; set; }
    }
}
