//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ItemMaster
    {
        [Required]
        public int ItemCode { get; set; }
        [Required]
        public string ItemName { get; set; }
        [Required]
        public int ItemType { get; set; }
        public string HSNCODE { get; set; }
        public string GstPer { get; set; }
        public string TypeName { get; set; }
        public IList<SelectListItem> itemtypes { get; set; }
    }
}
