//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceDetail
    {
        public int SalesDetailId { get; set; }
        public Nullable<int> Accountnumber { get; set; }
        public Nullable<int> Billno { get; set; }
        public Nullable<int> Itemdetailid { get; set; }
        public string Batchno { get; set; }
        public string Godown { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> salesprice { get; set; }
        public Nullable<int> disc { get; set; }
        public Nullable<int> discamt { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> SGST { get; set; }
        public Nullable<int> CGST { get; set; }
        public Nullable<int> IGST { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> SGSTAmt { get; set; }
        public Nullable<int> SGSTTaxableAmt { get; set; }
        public Nullable<int> CGSTAmt { get; set; }
        public Nullable<int> CGSTTaxableAmt { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<int> IGSTAmt { get; set; }
        public Nullable<int> IGSTTaxableAmt { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<decimal> totalamount { get; set; }
    }
}
