//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoDbEntities : DbContext
    {
        public DemoDbEntities()
            : base("name=DemoDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<AccountMaster> AccountMasters { get; set; }
        public DbSet<ItemMaster> ItemMasters { get; set; }
        public DbSet<ItemType> ItemTypes { get; set; }
        public DbSet<BatchMaster> BatchMasters { get; set; }
        public DbSet<GodownMaster> GodownMasters { get; set; }
        public DbSet<ItemDetail> ItemDetails { get; set; }
        public DbSet<UnitMaster> UnitMasters { get; set; }
        public DbSet<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public DbSet<SalesInvoiceMaster> SalesInvoiceMasters { get; set; }
    }
}
